/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2_estebansalazar;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author yogui
 */

public class SistemaEncuesta extends javax.swing.JFrame {
    
    Random rand = new Random();
int numAleatorio = rand.nextInt(100) + 1;

    
    public void setNumEncuesta(int numEncuesta) {
    NumEncuesta.setText(String.valueOf(numEncuesta));
}
    
     private int numEncuesta;
    private List<ClsEncuesta> listaEncuestas = new ArrayList<>();

    public SistemaEncuesta(int numEncuesta) {
        initComponents();
        
    }
    public SistemaEncuesta() {
        listaEncuestas = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NumEncuesta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        YearText = new javax.swing.JTextField();
        MailText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CarroPro = new javax.swing.JComboBox<>();
        Bagregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen2_estebansalazar/colorful-abstract-circle-background-free-vector.jpg"))); // NOI18N
        jLabel2.setText("ENCUESTA");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen2_estebansalazar/colorful-abstract-circle-background-free-vector.jpg"))); // NOI18N

        jLabel3.setText("Numero de encuesta");

        NumEncuesta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setText("Nombre completo");

        jLabel5.setText("Correo Electronico");

        jLabel6.setText("Edad");

        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        YearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearTextActionPerformed(evt);
            }
        });

        MailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailTextActionPerformed(evt);
            }
        });

        jLabel7.setText("Carro Promio");

        CarroPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        CarroPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarroProActionPerformed(evt);
            }
        });

        Bagregar.setText("Agregar");
        Bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarroPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MailText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YearText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(NumEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Bagregar))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NumEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(YearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CarroPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Bagregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarroProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarroProActionPerformed
        ClsEncuesta encuesta = new ClsEncuesta();
        String carroPropio = (String) CarroPro.getSelectedItem();
        encuesta.setTieneCarro(carroPropio);
    }//GEN-LAST:event_CarroProActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        ClsEncuesta encuesta = new ClsEncuesta();
        String nombre = NameText.getText();
        encuesta.setNombre(nombre);
        
        
    }//GEN-LAST:event_NameTextActionPerformed

    private void YearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearTextActionPerformed
          ClsEncuesta encuesta = new ClsEncuesta();
    String edadStr = YearText.getText();
    if (edadStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor ingrese una edad.");
        return;
    }
    int edad = Integer.parseInt(edadStr);
    encuesta.setEdad(edad);
          
          
    }//GEN-LAST:event_YearTextActionPerformed

    private void MailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailTextActionPerformed
        
        ClsEncuesta encuesta = new ClsEncuesta();
    String mailStr = MailText.getText();
    if (mailStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor ingrese una correo.");
        return;
    }
    int mail = Integer.parseInt(mailStr);
    encuesta.setEdad(mail);
    }//GEN-LAST:event_MailTextActionPerformed

    private void BagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagregarActionPerformed
         
// Obtener los datos de los campos correspondientes
    String nombre = NameText.getText();
    int edad = Integer.parseInt(YearText.getText());
    String correo = MailText.getText();
    String tieneCarro = (String) CarroPro.getSelectedItem();
    
     if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El campo nombre es obligatorio");
        return;
    }

    // Verificar que el campo edad no esté vacío y sea un número válido
    try {
        edad = Integer.parseInt(YearText.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El campo edad debe ser un número válido");
        return;
    }

    // Verificar que el campo correo no esté vacío
    if (correo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El campo correo es obligatorio");
        return;
    }

    // Crear un objeto ClsEncuesta y establecer sus atributos
   ClsEncuesta encuesta = new ClsEncuesta();
    encuesta.setNombre(NameText.getText());
    encuesta.setEdad(Integer.parseInt(YearText.getText()));
    encuesta.setCorreo(MailText.getText());
    encuesta.setTieneCarro(CarroPro.getSelectedItem().toString());
      // Generar y asignar número aleatorio al JLabel NumEncuesta
    Random rand = new Random();
    int numAleatorio = rand.nextInt(100) + 1;
    NumEncuesta.setText(String.valueOf(numAleatorio));
    
    listaEncuestas.add(encuesta);
    
    // Limpiar los campos de texto y el combo box
    NameText.setText("");
    YearText.setText("");
    MailText.setText("");
    CarroPro.setSelectedIndex(0);
    }//GEN-LAST:event_BagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagregar;
    private javax.swing.JComboBox<String> CarroPro;
    private javax.swing.JTextField MailText;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel NumEncuesta;
    private javax.swing.JTextField YearText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
